spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus1
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus1_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shahn2525@gmail.com
    password: xoeckbxjwiedizon
    properties:
      mail:
        smtp:
          starttls:
            enable: true